---
- name: Install Docker and Configure Nginx on EC2
  hosts: ec2 # The group defined in inventory.ini
  become: true # Run as sudo
  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add user to Docker group
      user:
        name: ubuntu
        group: docker
        append: yes

    - name: Pull the Docker image
      command: docker pull gitkeeper05/avinash:latest

    - name: Run the Docker container
      command: docker run -d --name random2 -p 5000:5000 gitkeeper05/avinash:latest

    - name: Configure Nginx reverse proxy
      copy:
        content: |
          server {
              listen 80;

              location / {
                  proxy_pass http://localhost:5000/;
              }
          }
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
        mode: "0644"

    - name: Test nginx configuration
      command: nginx -t
      notify:
        - Restart nginx

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
