name: CI/CD Pipeline that triggers terraform and ansible operations.

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials setting up AWS account to access infrastructure resources
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: "eu-west-1" # ireland

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.11.0 # Use the latest stable version or the specific version you need

      - name: Terraform init
        run: terraform init
        working-directory: ./terraform

      - name: Planning terraform script
        run: terraform plan -out=tfplan -var="ssh_public_key=${{ secrets.AWS_SSH_PUBLIC_KEY }}"
        working-directory: ./terraform

      - name: Running terrafrom script
        run: terraform apply -auto-approve
        working-directory: ./terraform

  ansible:
    name: "Ansible"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible-setup/inventory.ini ansible-setup/install-docker.yml
